name: CMake Build
on: [push, pull_request]

env:
  MODULE_PREFIX: gmcl
  MODULE_NAME: jellyfish_rpc

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - {
          name: "Windows 32Bit", artifact: "${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_win32.dll",
          cmakeargs: "-A Win32"
        }
        - {
          name: "Windows 64Bit", artifact: "${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_win64.dll",
          cmakeargs: "-A x64"
        }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      env:
        cmakeargs: ${{matrix.config.cmakeargs}}
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/cmake/cpp $cmakeargs

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target ${{env.MODULE_NAME}} --config MinSizeRel

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.config.artifact}}
        path: ${{runner.workspace}}\build\MinSizeRel\${{matrix.config.artifact}}